### ISSUE TITLE
Make compatible with newer version of pip

### ISSUE THREAD

**Issue by jbussemaker** [SMTorg/smt#98] opened 2018-07-09 09:28 UTC
Trying to install the package using version 10 of pip raises the following error:
AttributeError: Module Pip has no attribute 'main'

The temporary solution involves rolling back pip to version 9 (https://stackoverflow.com/a/49990889), but it would be better of course if the package is made compatible with the latest pip version.

**Comment by relf** [comment] 2018-09-04 09:28
I can not reproduce the bug in my environment. On Windows 64 with Python 3.6 and SMT repo cloned in smt directory I get:
```bash
(base) D:\rlafage\workspace>pip --version
pip 18.0 from d:\rlafage\miniconda3\lib\site-packages\pip (python 3.6)

(base) D:\rlafage\workspace>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

(base) D:\rlafage\workspace>pip install -e smt
Obtaining file:///D:/rlafage/workspace/smt
Requirement already satisfied: scikit-learn in d:\rlafage\miniconda3\lib\site-packages (from smt==0.2) (0.19.2)
Requirement already satisfied: pyDOE2 in d:\rlafage\miniconda3\lib\site-packages (from smt==0.2) (1.1.1)
Requirement already satisfied: matplotlib in d:\rlafage\miniconda3\lib\site-packages (from smt==0.2) (2.2.3)
Requirement already satisfied: numpydoc in d:\rlafage\miniconda3\lib\site-packages (from smt==0.2) (0.8.0)
Requirement already satisfied: six>=1.10 in d:\rlafage\miniconda3\lib\site-packages (from smt==0.2) (1.11.0)
Requirement already satisfied: scipy in d:\rlafage\miniconda3\lib\site-packages (from smt==0.2) (1.1.0)
Requirement already satisfied: numpy in d:\rlafage\miniconda3\lib\site-packages (from pyDOE2->smt==0.2) (1.15.1)
Requirement already satisfied: pytz in d:\rlafage\miniconda3\lib\site-packages (from matplotlib->smt==0.2) (2018.5)
Requirement already satisfied: cycler>=0.10 in d:\rlafage\miniconda3\lib\site-packages (from matplotlib->smt==0.2) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\rlafage\miniconda3\lib\site-packages (from matplotlib->smt==0.2) (1.0.1)
Requirement already satisfied: python-dateutil>=2.1 in d:\rlafage\miniconda3\lib\site-packages (from matplotlib->smt==0.2) (2.7.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in d:\rlafage\miniconda3\lib\site-packages (from matplotlib->smt==0.2) (2.2.0)
Requirement already satisfied: sphinx>=1.2.3 in d:\rlafage\miniconda3\lib\site-packages (from numpydoc->smt==0.2) (1.7.8)
Requirement already satisfied: Jinja2>=2.3 in d:\rlafage\miniconda3\lib\site-packages (from numpydoc->smt==0.2) (2.10)
Requirement already satisfied: setuptools in d:\rlafage\miniconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->smt==0.2) (39.2.0)
Requirement already satisfied: sphinxcontrib-websupport in d:\rlafage\miniconda3\lib\site-packages (from sphinx>=1.2.3->numpydoc->smt==0.2) (1.1.0)
Requirement already satisfied: docutils>=0.11 in d:\rlafage\miniconda3\lib\site-packages (from sphinx>=1.2.3->numpydoc->smt==0.2) (0.14)
Requirement already satisfied: snowballstemmer>=1.1 in d:\rlafage\miniconda3\lib\site-packages (from sphinx>=1.2.3->numpydoc->smt==0.2) (1.2.1)
Requirement already satisfied: colorama>=0.3.5; sys_platform == "win32" in d:\rlafage\miniconda3\lib\site-packages (from sphinx>=1.2.3->numpydoc->smt==0.2) (0.3.9)
Requirement already satisfied: imagesize in d:\rlafage\miniconda3\lib\site-packages (from sphinx>=1.2.3->numpydoc->smt==0.2) (1.0.0)
Requirement already satisfied: packaging in d:\rlafage\miniconda3\lib\site-packages (from sphinx>=1.2.3->numpydoc->smt==0.2) (17.1)
Requirement already satisfied: babel!=2.0,>=1.3 in d:\rlafage\miniconda3\lib\site-packages (from sphinx>=1.2.3->numpydoc->smt==0.2) (2.6.0)
Requirement already satisfied: requests>=2.0.0 in d:\rlafage\miniconda3\lib\site-packages (from sphinx>=1.2.3->numpydoc->smt==0.2) (2.18.4)
Requirement already satisfied: alabaster<0.8,>=0.7 in d:\rlafage\miniconda3\lib\site-packages (from sphinx>=1.2.3->numpydoc->smt==0.2) (0.7.11)
Requirement already satisfied: Pygments>=2.0 in d:\rlafage\miniconda3\lib\site-packages (from sphinx>=1.2.3->numpydoc->smt==0.2) (2.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in d:\rlafage\miniconda3\lib\site-packages (from Jinja2>=2.3->numpydoc->smt==0.2) (1.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in d:\rlafage\miniconda3\lib\site-packages (from requests>=2.0.0->sphinx>=1.2.3->numpydoc->smt==0.2) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in d:\rlafage\miniconda3\lib\site-packages (from requests>=2.0.0->sphinx>=1.2.3->numpydoc->smt==0.2) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in d:\rlafage\miniconda3\lib\site-packages (from requests>=2.0.0->sphinx>=1.2.3->numpydoc->smt==0.2) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in d:\rlafage\miniconda3\lib\site-packages (from requests>=2.0.0->sphinx>=1.2.3->numpydoc->smt==0.2) (2018.8.24)
Installing collected packages: smt
  Found existing installation: smt 0.2
    Uninstalling smt-0.2:
      Successfully uninstalled smt-0.2
  Running setup.py develop for smt
Successfully installed smt
```
Could you give some details about your environment? Or maybe try again with latest version from SMT repo?

**Comment by relf** [comment] 2018-09-27 10:40
I think the error message was due to Cython not being installed. I close the issue.

**Closed by relf** 2018-09-27 10:40 UTC
